### PR TITLE
This should fix deep sleep bug on 8.1

### PR DESCRIPTION
**Pull request by jneto3000**
Bug: 32180327

### CODE REVIEW

**Comment by DD3Boh** [comment]
Uhm, this seems interesting, I will check it out and tell you, even if maybe not today just because it's Christmas xD

**Comment by YaroST12** [comment]
@jneto3000 Picked it today. Seems legit.

**Comment by YaroST12** [comment]
Second commit, the defconfig one, is not required. It's disabled by default

**Comment by DD3Boh** [comment]
I agree with you @YaroST12 on the second comment
Will try the commit and see

**Comment by jneto3000** [comment]
@YaroST12 That's what I thought, thanks. 
Before this commit I was having only one cycle of deepsleep, after turning on screen the system stopped going on deepsleep. Now I'm at maybe 7 or 8 cycles and deepsleep seems to work fine.

**Comment by YaroST12** [comment]
@jneto3000 seems like not only I am following Sony repo yeah?)

**Comment by jneto3000** [comment]
@YaroST12 yeah but I haven't got it from there, I've got it from here:
https://gerrit.omnirom.org/#/c/27743/

**Comment by DD3Boh** [comment]
seems like working.
Now I'll just push the commit normally writing in the commit message where I picked it from (aka this pull request)

**Comment by YaroST12** [comment]
@DD3Boh Pick it from my repo, just [ushed it.

**Comment by DD3Boh** [comment]
Let's close the pull request with 7be50e7b0fcc7638afa537eae7ec3eb54b73204a

**Comment by FireLord** [comment]
@DD3Boh pro tits

**Pull request closed without merging**
